#pragma config(Hubs,  S1, MatrxRbtcs, none,     none,     none)
#pragma config(Sensor, S2,     gyroSensor,     sensorI2CHiTechnicGyro)
#pragma config(Sensor, S3,     sensorIR,       sensorI2CCustom)
#pragma config(Sensor, S4,     sensorIR2,      sensorI2CCustom)
#pragma config(Motor,  mtr_Matrix_S1_1, motorBack,     tmotorMatrix, PIDControl)
#pragma config(Motor,  mtr_Matrix_S1_2, motorLeft,     tmotorMatrix, PIDControl)
#pragma config(Motor,  mtr_Matrix_S1_3, motorRight,    tmotorMatrix, PIDControl)
#pragma config(Motor,  mtr_Matrix_S1_4, motorFront,    tmotorMatrix, PIDControl)
#pragma config(Servo,  srvo_Matrix_S1_1, servo1,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_2, servo2,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_3, servo3,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_4, servo4,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "irSeeker_lib.h"
#include "HolonomicDrive.c"
#include "SmoothMoves.c"
//#include "JoystickDriver.c"
#include "Gyro.c"
#include "BlueToothCom/BTRawComm.h"

task main()
{

//setBluetoothRawDataMode();
setUpHighSpeedLink();
wait1Msec(50);

//ubyte transmitBuffer[1];
	//waitForStart();

	IRSeekerInfo irSeeker;
	IRSeekerInfo irSeeker2;

	initializeHolonimicDrive(motorFront, motorRight, motorBack, motorLeft);
	initialieIRSeeker(irSeeker, sensorIR);
	initialieIRSeeker(irSeeker2, sensorIR2);
	addGyroControl(gyroSensor);

	eraseDisplay();

	while(true) {
		//getJoystickSettings(joystick);
		eraseDisplay();

		nxtDisplayTextLine(1,"%4f", irSeeker.dir_ac);

		initialiseIRSeekerPacked();

		packInt(0);
		packInt(irSeeker.dir_ac);
		packInt(irSeeker.acS1);
		packInt(irSeeker.acS2);
		packInt(irSeeker.acS3);
		packInt(irSeeker.acS4);
		packInt(irSeeker.acS5);

		transmitPackedMessage(BROADCAST);

		wait10Msec(1);

		initialiseIRSeekerPacked();

		packInt(1);
		packInt(irSeeker2.dir_ac);
		packInt(irSeeker2.acS1);
		packInt(irSeeker2.acS2);
		packInt(irSeeker2.acS3);
		packInt(irSeeker2.acS4);
		packInt(irSeeker2.acS5);

		transmitPackedMessage(BROADCAST);

		wait10Msec(1);
		//sendMessage(irSeeker.dir_ac + 100);
		//transmitBuffer[0] = irSeeker.dir_ac;
		//nxtWriteRawBluetooth(transmitBuffer, 1);
		//nxtWriteRawBluetooth(irSeeker.dcS3, 1);

		//sendRobot(joystick);
		//rotate(-joystick.joy1_x2);

		//updateHolonomicDrive();

		updateIRSeeker(irSeeker);
		updateIRSeeker(irSeeker2);

		if (joy1Btn(2) == 1) {
			resetGyro(gyro);
		}
	}
}
