//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// SendSimpleData.c
//
// Test sending single data values to a receipient
// (either another NXT or a PC/Mac)
//
// The data values change each iteration, so you should
// see changing values on the receiver.
//
// Run this on a NXT with a NXTBee attached to port 4.
//
// To receive data on another NXT run the Receiver.c program
// on the NXT. To receive data on your PC/Mac run the Reader.pde
// Processing sketch. You can run two receivers concurrently,
// they should both get the same values sent by this program.
//
// Copyright 2012 Mark Crosbie mark@mastincrosbie.com
// http://www.mastincrosbie.com/Marks_LEGO_projects
//

#include "NXTBeeComms.h"

// default broadcast this message
#define ADDR BROADCAST

task main() {

  long lvalue;
  int ivalue;
  byte bvalue;
  string s;

  eraseDisplay();
  bNxtLCDStatusDisplay = false;
  setupHighSpeedLink();

  nxtDisplayString(1, "NXTBee Send Test");

  bvalue = 123;
  lvalue = -12345678;
  ivalue = -32768;

  while(nNxtButtonPressed != kEnterButton) {


      nxtScrollText("Sending %d   ", ivalue);
      transmitInt(ADDR, ivalue--);
      wait10Msec(50);

      nxtScrollText("Sending %d   ", lvalue);
      transmitLong(ADDR, lvalue++);
      wait10Msec(50);

      nxtScrollText("Sending %d   ", bvalue);
      transmitByte(ADDR, bvalue++);
      wait10Msec(50);

 }

}
